### ISSUE TITLE
Bitcoin trading strategy with RF, where is the actual signal output for the most recent time stamp?

### ISSUE THREAD

**Issue by cody-vandervoort** [tatsath/fin-ml#4]
Okay so say I want to use this on the data up until today, rather than just the signal of the short ema higher than the long ema, how do i combine the signal of all of the features to then come up with the binary decision to buy or sell? All that I am seeing is the binary decision for the ['signal'] column which is only based on the ema's, how do i go about retreiving the signal that combines all of the features, I see where thing's get backtested and we see the final results but how do i dig into the most recent time stamp to tell if it's a buy or sell signal based on all of the features rather than just the ema's for todays price? I'm confused of how to go about extracting the signal to actually use it in production, I would greatly appreciate your response, thank you.

**Comment by cody-vandervoort** [comment]
After going through and reading and doing the exercises for Hands on Ml:2 I come back just to clarify my question, for time series do i need to create a new factor column to say that the market went up or down, as for the classification for the examles in hands on ml2 its predicting flowers and the mnist data set, from stefan janson's ml4t which is just too complex for me to pick up even though i've been working through it for like a year, the example he uses makes like a rate of change for periods of 5 21 30 40 60 ect; which seems similar to the rate of change indicator, but how do i get the answer to buy or sell, from what I see in the example you have you make the signal if the ema's cross right, so when i am looking at the comparison from the hands on ml2 example when we're using the flowers for which is a hard answer that if the length is this and the width is this then it should be a flower, so i understand how we hit the predictor with the new data and we get back the flower type, since the flower name is hard coded in the training data, but i'm missing where and how I get back an answer stating that the market will go up or down over the next time period when I give it the new data, I just can't seem to pick up where i get the answer back of whether it's going to bullish for the new predicted time period, I feel like i understand the concepts well from hands on ml 2 but still very confused about the signal in the example, if this is the entirety of the decision and you just showed us how important the feature is and why we should rely on it? are we combining the features together to make a more accurate final prediction, with the signal just being one of them? As i desire to be able to add a whole bunch of my own custom indicators but im confused on how I get back the binary answer of if the market will go up or down with my prediction, where do i code this in, do i need to make a new column on the data saying it went up or it went down, in place of the iris flower so it knows when it sees this data it went up or to stay flat, from what im seeing in the code you have here is that the signal is the buy or sell and the final answer i should get back when hitting the predictor I must be wrong can you please help me get over this hurdle?

**Comment by tatsath** [comment]
I don't understand your question completely. In our case study we have used
short term vs. long term to define the signal. You can use any customized
approach for the signal.

Thanks,
Hariom
